[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[lint]
exclude_lints = [
    "mixed-case-variable",
    "pascal-case-struct",
    "screaming-snake-case-immutable",
    "mixed-case-function",
    "screaming-snake-case-const",
    "unaliased-plain-import",
    "erc20-unchecked-transfer",
    "unused-import",
]
